openapi: 3.1.0
info:
  title: Skribble API v3
  version: 3.0.0
  description: |
    The Skribble API v3 documentation describes the publicly available Skribble
    API version 3. The API allows businesses and teams of any size to integrate
    the e-signing solution of Skribble with internal systems, software, or SaaS
    solutions. It provides a simple interface to create and manage signature
    requests programmatically. Signature requests define who signs what and
    describe the document flow between participants. Actual signing occurs in
    the Skribble web application.

    API v3 provides ...
  license:
    name: Apache 2.0
    identifier: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.skribble.com/en-eu/terms-of-use/
  contact:
    name: Skribble Engineering
    url: https://skribble.com
    email: info@skribble.com
servers:
  - url: https://api.skribble.com/v3
    description: Production - Switzerland
  - url: https://api.skribble.de/v3
    description: Production - Germany
  - url: https://api.scribital.com/v3
    description: Staging - Switzerland
  - url: https://api.scribital.de/v3
    description: Staging - Germany
paths:
  /access/login:
    $ref: ../sign_v2/paths/access_login.yaml
  /signature-requests:
    $ref: ./paths/signature-requests.yaml
  /signature-requests/{SR_ID}:
    $ref: ../sign_v2/paths/signature-requests_{SR_ID}.yaml
  /signature-requests/{SR_ID}/initiate:
    $ref: ./paths/signature-requests_{SR_ID}_initiate.yaml
  /signature-requests/{SR_ID}/withdraw:
    $ref: ../sign_v2/paths/signature-requests_{SR_ID}_withdraw.yaml
  /signature-requests/{SR_ID}/remind:
    $ref: ../sign_v2/paths/signature-requests_{SR_ID}_remind.yaml
  /signature-requests/{SR_ID}/report:
    $ref: ../sign_v2/paths/signature-requests_{SR_ID}_report.yaml
  /signature-requests/{SR_ID}/callbacks:
    $ref: ../sign_v2/paths/signature-requests_{SR_ID}_callbacks.yaml
  /signature-requests/{SR_ID}/attachments:
    $ref: ../sign_v2/paths/signature-requests_{SR_ID}_attachments.yaml
  /signature-requests/{SR_ID}/attachments/{ATTACHMENT_ID}/content:
    $ref: ../sign_v2/paths/signature-requests_{SR_ID}_attachments_{ATTACHMENT_ID}_content.yaml
  /signature-requests/{SR_ID}/attachments/{ATTACHMENT_ID}:
    $ref: ../sign_v2/paths/signature-requests_{SR_ID}_attachments_{ATTACHMENT_ID}.yaml
  /signature-requests/{SR_ID}/signatures:
    $ref: ./paths/signature-requests_{SR_ID}_signatures.yaml
  /signature-requests/{SR_ID}/signatures/{SID}:
    $ref: ../sign_v2/paths/signature-requests_{SR_ID}_signatures_{SID}.yaml
  /signature-requests/{SR_ID}/documents:
    $ref: ./paths/signature-requests_{SR_ID}_documents.yaml
  /signature-requests/{SR_ID}/documents/{DOC_ID}:
    $ref: ./paths/signature-requests_{SR_ID}_documents_{DOC_ID}.yaml
  /seal:
    $ref: ../sign_v2/paths/seal.yaml
  /documents:
    $ref: ../sign_v2/paths/documents.yaml
  /documents/{DOC_ID}:
    $ref: ../sign_v2/paths/documents_{DOC_ID}.yaml
  /documents/{DOC_ID}/content:
    $ref: ../sign_v2/paths/documents_{DOC_ID}_content.yaml
  /documents/{DOC_ID}/pages/{PAGE_ID}:
    $ref: ../sign_v2/paths/documents_{DOC_ID}_pages_{PAGE_ID}.yaml
  /sendto:
    $ref: ../sign_v2/paths/sendto.yaml
  /sendto/{SEND_TO_ID}/track:
    $ref: ../sign_v2/paths/sendto_{SEND_TO_ID}_track.yaml
  /sendto/{SEND_TO_ID}/download:
    $ref: ../sign_v2/paths/sendto_{SEND_TO_ID}_download.yaml
  /sendto/{SEND_TO_ID}:
    $ref: ../sign_v2/paths/sendto_{SEND_TO_ID}.yaml
  /user/signature-qualities:
    $ref: ../sign_v2/paths/user_signature-qualities.yaml
  /activities/signatures:
    $ref: ../sign_v2/paths/activities_signatures.yaml
  /management/health:
    $ref: ../sign_v2/paths/management_health.yaml
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Access
    description: |
      Endpoints for authentication, authorization, and user access management
  - name: Document
    description: |
      Endpoints for Documents
  - name: Signature
    description: |
      Endpoints related to creating and managing signature requests
  - name: Signature Attachment
    description: |
      Endpoints for Attachments
  - name: Signature Tracking
    description: |
      Endpoints related to tracking signature requests
  - name: Seal
    description: |
      Endpoints for Seals
  - name: SendTo
    description: |
      Endpoints for Send-To
  - name: User
    description: |
      Endpoints for Users
  - name: Report
    description: |
      Endpoints for Reporting
  - name: Monitoring
    description: |
      Endpoints for Monitoring
