openapi: 3.1.0
info:
  title: Skribble API v2
  version: 2.1.0
  description: >-
    The Skribble API v2 documentation describes the publicly available Skribble
    API version 2. The API allows businesses and teams of any size to integrate
    the e-signing solution of Skribble with internal systems, software, or SaaS
    solutions. It provides a simple interface to create and manage signature
    requests programmatically. Signature requests define who signs what and
    describe the document flow between participants. Actual signing occurs in
    the Skribble web application.

    To get started, set up Skribble Business. Feedback and questions can be sent
    to the Google Group public-api-users@skribble.com.

    API v2 provides enhanced features including creating, finding, and
    triggering signature requests, user and monitoring details, and reporting
    activities. It maintains backward compatibility with API v1 but upgrading is
    recommended to access the latest features. Migration from API v1 involves
    updating base URLs, renaming fields, and adjusting visual signature
    positions.
  license:
    name: Apache 2.0
    identifier: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.skribble.com/en-eu/terms-of-use/
  contact:
    name: Skribble Engineering
    url: https://skribble.com
    email: info@skribble.com
servers:
  - url: https://api.skribble.com/v2
    description: Production - Switzerland
  - url: https://api.skribble.de/v2
    description: Production - Germany
  - url: https://api.scribital.com/v2
    description: Staging - Switzerland
  - url: https://api.scribital.de/v2
    description: Staging - Germany
paths:
  /access/login:
    $ref: paths/access_login.yaml
  /signature-requests:
    $ref: paths/signature-requests.yaml
  /signature-requests/{SR_ID}:
    $ref: paths/signature-requests_{SR_ID}.yaml
  /signature-requests/{SR_ID}/withdraw:
    $ref: paths/signature-requests_{SR_ID}_withdraw.yaml
  /signature-requests/{SR_ID}/remind:
    $ref: paths/signature-requests_{SR_ID}_remind.yaml
  /signature-requests/{SR_ID}/callbacks:
    $ref: paths/signature-requests_{SR_ID}_callbacks.yaml
  /signature-requests/{SR_ID}/attachments:
    $ref: paths/signature-requests_{SR_ID}_attachments.yaml
  /signature-requests/{SR_ID}/attachments/{ATTACHMENT_ID}/content:
    $ref: paths/signature-requests_{SR_ID}_attachments_{ATTACHMENT_ID}_content.yaml
  /signature-requests/{SR_ID}/attachments/{ATTACHMENT_ID}:
    $ref: paths/signature-requests_{SR_ID}_attachments_{ATTACHMENT_ID}.yaml
  /signature-requests/{SR_ID}/signatures:
    $ref: paths/signature-requests_{SR_ID}_signatures.yaml
  /signature-requests/{SR_ID}/signatures/{SID}:
    $ref: paths/signature-requests_{SR_ID}_signatures_{SID}.yaml
  /seal:
    $ref: paths/seal.yaml
  /documents:
    $ref: paths/documents.yaml
  /documents/{DOC_ID}:
    $ref: paths/documents_{DOC_ID}.yaml
  /documents/{DOC_ID}/content:
    $ref: paths/documents_{DOC_ID}_content.yaml
  /documents/{DOC_ID}/pages/{PAGE_ID}:
    $ref: paths/documents_{DOC_ID}_pages_{PAGE_ID}.yaml
  /sendto:
    $ref: paths/sendto.yaml
  /sendto/{SEND_TO_ID}/track:
    $ref: paths/sendto_{SEND_TO_ID}_track.yaml
  /sendto/{SEND_TO_ID}/download:
    $ref: paths/sendto_{SEND_TO_ID}_download.yaml
  /sendto/{SEND_TO_ID}:
    $ref: paths/sendto_{SEND_TO_ID}.yaml
  /user/signature-qualities:
    $ref: paths/user_signature-qualities.yaml
  /activities/signatures:
    $ref: paths/activities_signatures.yaml
  /management/health:
    $ref: paths/management_health.yaml
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Access
    description: >-
      Endpoints for authentication, authorization, and user access management
  - name: Document
    description: >-
      Endpoints for Documents
  - name: Signature
    description: >-
      Endpoints related to creating and managing signature requests
  - name: Signature Attachment
    description: >-
      Endpoints for Attachments
  - name: Signature Tracking
    description: >-
      Endpoints related to tracking signature requests
  - name: Seal
    description: >-
      Endpoints for Seals
  - name: SendTo
    description: >-
      Endpoints for Send-To
  - name: User
    description: >-
      Endpoints for Users
  - name: Report
    description: >-
      Endpoints for Reporting
  - name: Monitoring
    description: >-
      Endpoints for Monitoring
