openapi: 3.0.3
info:
  description: 'All requests to the Skribble API must be authorized. To obtain an
    access token, please use the <b>/access/login</b> resource. Then add the access
    token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>'
  version: '2.0'
  title: Sign API
  contact:
    name: Skribble Engineering
    url: https://skribble.com
    email: info@skribble.com
  license:
    name: Skribble License Version 1.0
servers:
- url: https://api.skribble.com/v2
paths:
  $ref: ./paths/paths.yaml
components:
  $ref: ./components/components.yaml
tags: []
