openapi: 3.1.0
info:
  title: Validation and Conversion Service API
  version: 1.1.5
  description: >-
    This API documentation describes the publicly available Validation and
    Conversion Service of Skribble.
  license:
    name: Apache 2.0
    identifier: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.skribble.com/en-eu/terms-of-use/
  contact:
    name: Skribble Engineering
    url: https://skribble.com
    email: info@skribble.com
servers:
  - url: https://document-validation.skribble.com/v1
    description: Production - Switzerland
  - url: https://document-validation.skribble.de/v1
    description: Production - Germany
  - url: https://document-validation.scribital.com/v1
    description: Staging - Switzerland
  - url: https://document-validation.scribital.de/v1
    description: Staging - Germany
tags:
  - name: Access
    description: Endpoints for authentication, authorization, and user access management.
  - name: Validation
    description: Endpoints to validate documents, data formats, and signatures.
  - name: Additional Information
    description: Endpoints providing extra metadata or supplementary details for documents.
  - name: Reports
    description: Endpoints for generating, retrieving, and managing reports related to document processing.
  - name: Tooling
    description: Utility endpoints and tools that assist with document handling or integration.
  - name: Billing and Credits
    description: Endpoints for managing account credits, billing information, and payment operations.
paths:
  /access/login:
    $ref: paths/access_login.yaml
  /validate/document:
    $ref: paths/validate_document.yaml
  /validate/signature:
    $ref: paths/validate_signature.yaml
  /validate/certificate:
    $ref: paths/validate_certificate.yaml
  /validate/{id}:
    $ref: paths/validate_{id}.yaml
  /infos/{id}/validation:
    $ref: paths/infos_{id}_validation.yaml
  /infos/{id}/signers:
    $ref: paths/infos_{id}_signers.yaml
  /infos/{id}/format:
    $ref: paths/infos_{id}_format.yaml
  /reports/{id}/skribble:
    $ref: paths/reports_{id}_skribble.yaml
  /reports/{id}/etsi:
    $ref: paths/reports_{id}_etsi.yaml
  /tooling/upload:
    $ref: paths/tooling_upload.yaml
  /tooling/process/{id}/check:
    $ref: paths/tooling_process_{id}_check.yaml
  /tooling/process/{id}/conform:
    $ref: paths/tooling_process_{id}_conform.yaml
  /tooling/process/{id}/compress:
    $ref: paths/tooling_process_{id}_compress.yaml
  /tooling/process/{id}/spotsigners:
    $ref: paths/tooling_process_{id}_spotsigners.yaml
  /tooling/{id}:
    $ref: paths/tooling_{id}.yaml
  /billing/credits/infos:
    $ref: paths/billing_credits_infos.yaml
  /billing/credits/usage:
    $ref: paths/billing_credits_usage.yaml
  /billing/credits/invoiced:
    $ref: paths/billing_credits_invoiced.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT